version: '2'
services:
    quack-claimer:
        build:
            context: .
        container_name: quack-claimer
        ports:
            - '8180:4000' # map 80 in container => 3000 in local
        restart: always
        volumes:
            - claimer:/app
volumes:
    claimer:
